version: '3.8'
services:
  code-server:
    container_name: "${CONTAINER_NAME}"
    build:
      context: .
      args:
        BASE: ${BASE}
        VERSION: ${VERSION}
        DISTRO: ${DISTRO}
    ports:
      - "${CODE_PORT}:8080"
    volumes:
      - code-data:/home/coder/project

volumes:
  code-data:
