version: '3.8'
services:
  code-server:
    build:
      context: .
      args:
        GIT_BRANCH: ${GIT_BRANCH:-dev}
        GIT_REPO: ${GIT_REPO:-https://github.com/tuusuario/turepo.git}
    ports:
      - "${CODE_PORT}:8080"
    volumes:
      - code-data:/home/coder/project
    environment:
      - GIT_BRANCH=${GIT_BRANCH:-dev}
      - GIT_REPO=${GIT_REPO:-https://github.com/tuusuario/turepo.git}

volumes:
  code-data:
